# Site settings
author: Laura Radville
title: Laura's Blog
header-img: img/home-bg.png
email: laura.radville@gmail.com
copyright_name: Laura Radville
description: > # this means to ignore newlines until "baseurl:"
  A journey in becoming a software engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  radville

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
